gestures = {
    "index_up": "index finger moves upward",
    "index_up_left": "Index finger moves up and left",
    "index_up_right": "Index finger moves up and to the right",
    "index_left": "Move the index finger to the left, both hands can",
    "index_right": "Move the index finger to the right, both hands can",
    "index_down": "Move the lower part of the index finger, both hands can",
    "index_down_left": "Move the index finger to the lower left, both hands can",
    "index_down_right": "Move the index finger to the lower right, both hands can",
    "ok_gesture": "OK gesture, can be used by both left and right hands",
    "separate_lr": "Separate left and right",
    "together_lr": "left and right together",
    "cross_index": "Cross two index fingers",
    "palm_out_right": "Palms facing outward, turn to the right, both left and right hands can",
    "palm_out_left": "With the palm facing outward, turn it to the left, both hands can",
    "palm_side_right": "Keep your palms upright and turn your palms to the side to the right, both left and right hands can",
    "palm_side_left": "Keep your palms upright and turn your palms to the side to the left, both hands can be used",
    "set_trigger": "Set trigger, suitable for both left and right hands",
    "set_select_trigger": "When the set selection is triggered, the index finger stays on the circle, and an exclamation mark of the corresponding color appears on the person's face and head. The exclamation mark is made larger, and it can be used by both left and right hands.",
    "set_trigger_2": "Set trigger, suitable for both left and right hands",
    "set_select_trigger_2": "Set selection is triggered again, available for both left and right hands",
    "scissor_hands": "Scissor hands, suitable for both left and right hands",
    "fist": "Make a fist, either left or right hand",
    "index_thumb_spread": "The index finger and thumb are spread apart, suitable for both left and right hands",
    "index_thumb_close": "The index finger and thumb are close together, either left or right hand",
    "palm_vertical": "Open your palms vertically, either left or right hand",
    "palm_l_shape": "The palms should be upright in an L shape, suitable for both left and right hands"
}